-- Color pairs:
-- TITLE_COLOR_PAIR,
-- FILE_LINE_COLOR_PAIR,
-- DIRECTORY_LINE_COLOR_PAIR,
-- SELECTED_LINE_COLOR_PAIR,
-- BROWSER_COLOR_PAIR,
-- SEPERATOR_COLOR_PAIR,
-- IMAGE_BORDER_COLOR_PAIR,
-- COLOR_PAIR_DEFAULT,
-- REVERSE_DEFAULT_COLOR_PAIR,
-- VISUALIZER_BACKGROUND_COLOR_PAIR,
-- CYAN_BLACK_COLOR_PAIR,
-- BLUE_BLACK_COLOR_PAIR,
-- MAGENTA_BLACK_COLOR_PAIR,
-- GREEN_BLACK_COLOR_PAIR,
-- YELLOW_BLACK_COLOR_PAIR,
-- RED_BLACK_COLOR_PAIR,

-- Keys:
-- VOLUME_DOWN_KEY,
-- VOLUME_UP_KEY,
-- PAUSE_KEY,
-- BROWSER_WIN_KEY,
-- VISUALIZER_WIN_KEY,
-- QUIT_KEY,
-- SEEK_LEFT_KEY,
-- SEEK_RIGHT_KEY
-- UP_LINE_KEY,
-- DOWN_LINE_KEY,
-- SELECT_KEY,
-- ADD_TO_LIBRARY_KEY,
-- GLOBAL_SUPER_KEY,
-- GLOBAL_CONTROL_KEY,
-- GLOBAL_ALT_KEY,

-- Examples
-- SetColorPair(TITLE_COLOR_PAIR, -1, COLOR_BLUE)
-- SetHotkey(PAUSE_KEY, string.byte("p", 1))

SetStartDirectory("/home/toga")
UseLastFM(1, "togahimikoluv", "pass")
SetGlobalKey(GLOBAL_ALT_KEY)
